import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export { LanguageContext };

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    nav: {
      home: 'Home',
      buyCars: 'Buy Cars',
      askAI: 'Ask AI',
      about: 'About Us',
      contact: 'Contact Us',
      signIn: 'Sign In',
    },
    home: {
      title: 'Find Your Perfect Car',
      subtitle: 'Your trusted marketplace for buying and selling cars',
      description: 'Browse thousands of verified listings, connect with sellers, and drive away with confidence.',
      ctaBuy: 'Browse Cars',
      ctaAskAI: 'or Ask AI',
      featuresTitle: 'Why Choose WheelWise?',
      feature1Title: 'Verified Listings',
      feature1Desc: 'All cars are verified and checked for quality',
      feature2Title: 'Secure Transactions',
      feature2Desc: 'Safe and secure payment processing',
      feature3Title: 'Expert Support',
      feature3Desc: '24/7 customer support to help you',
      statsTitle: 'Trusted by Thousands',
      statsCars: 'Active Listings',
      statsUsers: 'Happy Users',
      statsDeals: 'Successful Deals',
    },
    askAI: {
      title: 'Ask AI Assistant',
      subtitle: 'Get instant answers to your car-related questions',
      welcomeTitle: 'How can I help you today?',
      welcomeText: 'Ask me anything about cars, buying tips, maintenance, comparisons, and more!',
      suggestedTitle: 'Try asking:',
      suggestedQuestions: [
        "What's the best family SUV under $30,000?",
        "How do I check if a used car has been in an accident?",
        "What should I look for when buying a used car?",
        "Compare sedan vs SUV for city driving"
      ],
      inputPlaceholder: 'Type your question here...',
      sendButton: 'Send',
      clearChat: 'Clear Chat',
      sampleResponse: "I'm here to help you with car-related questions! This is a placeholder response. In the future, I'll be powered by AI to provide detailed answers about car buying, maintenance, comparisons, and more."
    },
    buyCars: {
      title: 'Browse Cars',
      subtitle: 'Find your perfect car from our collection',
      searchPlaceholder: 'Search by brand or model...',
      filters: 'Filters',
      clearFilters: 'Clear All',
      brandLabel: 'Brand',
      bodyTypeLabel: 'Body Type',
      fuelTypeLabel: 'Fuel Type',
      colorLabel: 'Color',
      yearLabel: 'Year',
      kmLabel: 'Kilometers',
      priceLabel: 'Price ($)',
      resultsCount: 'Showing',
      cars: 'cars',
      noResults: 'No cars found',
      noResultsText: 'Try adjusting your filters or search query',
      viewOffer: 'See the Offer'
    },
    carDetail: {
      notFound: 'Car not found',
      backToBrowse: 'Back to Browse',
      year: 'Year',
      bodyType: 'Body Type',
      fuelType: 'Fuel Type',
      transmission: 'Transmission',
      kilometers: 'Kilometers',
      power: 'Power',
      color: 'Color',
      location: 'Location',
      features: 'Features',
      contactSeller: 'Contact Seller',
      scheduleTest: 'Schedule Test Drive'
    },
    auth: {
      loginTitle: 'Welcome Back',
      loginSubtitle: 'Sign in to your WheelWise account',
      registerTitle: 'Create Account',
      registerSubtitle: 'Join WheelWise today',
      name: 'Full Name',
      namePlaceholder: 'Enter your full name',
      email: 'Email Address',
      emailPlaceholder: 'Enter your email',
      password: 'Password',
      passwordPlaceholder: 'Enter your password',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Confirm your password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      loginButton: 'Sign In',
      registerButton: 'Create Account',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      signUp: 'Sign Up',
      signIn: 'Sign In',
      orContinue: 'or continue with',
      nameRequired: 'Name is required',
      emailRequired: 'Email is required',
      emailInvalid: 'Email is invalid',
      passwordRequired: 'Password is required',
      passwordLength: 'Password must be at least 6 characters',
      passwordMatch: 'Passwords do not match',
    },
    contact: {
      title: 'Contact Us',
      subtitle: 'Get in touch with our team. We\'re here to help!',
      emailTitle: 'Email',
      phoneTitle: 'Phone',
      addressTitle: 'Address',
      formTitle: 'Send us a Message',
      name: 'Full Name',
      namePlaceholder: 'John Doe',
      email: 'Email Address',
      emailPlaceholder: 'john@example.com',
      phone: 'Phone Number',
      phonePlaceholder: '+36 20 123 4567',
      subject: 'Subject',
      subjectPlaceholder: 'How can we help?',
      message: 'Message',
      messagePlaceholder: 'Tell us more about your inquiry...',
      submitButton: 'Send Message',
      successTitle: 'Message Sent!',
      successMessage: 'Thank you for contacting us. We\'ll get back to you soon.',
      nameRequired: 'Name is required',
      emailRequired: 'Email is required',
      emailInvalid: 'Email is invalid',
      subjectRequired: 'Subject is required',
      messageRequired: 'Message is required',
      messageLength: 'Message must be at least 10 characters',
    },
    about: {
      title: 'About WheelWise',
      subtitle: 'Your Trusted Platform for Buying and Selling Quality Vehicles',
      missionTitle: 'Our Mission',
      missionText: 'At WheelWise, we believe that buying or selling a car should be a simple, transparent, and enjoyable experience. Our mission is to revolutionize the automotive marketplace by connecting buyers and sellers through a platform built on trust, quality, and innovation.',
      missionText2: 'We are committed to providing verified listings, secure transactions, and exceptional customer support to ensure that every user finds their perfect vehicle with confidence.',
      valuesTitle: 'Our Core Values',
      value1Title: 'Trust & Transparency',
      value1Desc: 'Every listing is verified and transparent. We ensure all information is accurate and trustworthy.',
      value2Title: 'Security First',
      value2Desc: 'Your safety is our priority. We use advanced security measures to protect your data and transactions.',
      value3Title: 'Customer Focused',
      value3Desc: 'Our dedicated support team is available 24/7 to assist you throughout your journey.',
      value4Title: 'Innovation',
      value4Desc: 'We continuously improve our platform with the latest technology to enhance your experience.',
      statsTitle: 'Our Impact',
      statCars: 'Cars Listed',
      statUsers: 'Happy Users',
      statDeals: 'Successful Deals',
      statSatisfaction: 'Satisfaction Rate',
      teamTitle: 'Meet Our Team',
      teamDescription: 'Dedicated professionals working together to make your car buying and selling experience exceptional.',
      ceoName: 'John Smith',
      ceoRole: 'CEO & Founder',
      ctoName: 'Sarah Johnson',
      ctoRole: 'CTO',
      cooName: 'Michael Chen',
      cooRole: 'COO',
      ctaTitle: 'Ready to Get Started?',
      ctaText: 'Join thousands of satisfied users and experience the future of car buying and selling.',
      ctaBrowse: 'Browse Cars',
      ctaAskAI: 'Ask AI',
    },
  },
  hu: {
    nav: {
      home: 'Főoldal',
      buyCars: 'Autók Vásárlása',
      askAI: 'AI Tanács',
      about: 'Rólunk',
      contact: 'Kapcsolat',
      signIn: 'Bejelentkezés',
    },
    home: {
      title: 'Találd Meg a Tökéletes Autót',
      subtitle: 'A megbízható piactér autók vásárlásához és eladásához',
      description: 'Böngéssz több ezer ellenőrzött hirdetés között, lépj kapcsolatba eladókkal, és vezess el bizalommal.',
      ctaBuy: 'Autók Böngészése',
      ctaAskAI: 'vagy kérj tanácsot AI-tól',
      featuresTitle: 'Miért a WheelWise-t Válaszd?',
      feature1Title: 'Ellenőrzött Hirdetések',
      feature1Desc: 'Minden autó ellenőrzött és minőségileg ellenőrzött',
      feature2Title: 'Biztonságos Tranzakciók',
      feature2Desc: 'Biztonságos és megbízható fizetési feldolgozás',
      feature3Title: 'Szakértői Támogatás',
      feature3Desc: '24/7 ügyfélszolgálat, hogy segítsünk neked',
      statsTitle: 'Ezrek Bíznak Bennünk',
      statsCars: 'Aktív Hirdetés',
      statsUsers: 'Elégedett Felhasználó',
      statsDeals: 'Sikeres Üzlet',
    },
    askAI: {
      title: 'AI Asszisztens',
      subtitle: 'Kapj azonnali válaszokat autókkal kapcsolatos kérdéseidre',
      welcomeTitle: 'Hogyan segíthetek ma?',
      welcomeText: 'Kérdezz bármit az autókról, vásárlási tippekről, karbantartásról, összehasonlításokról és még sok másról!',
      suggestedTitle: 'Próbáld ki:',
      suggestedQuestions: [
        "Mi a legjobb családi SUV 10 millió forint alatt?",
        "Hogyan ellenőrizzem, hogy egy használt autó volt-e balesetben?",
        "Mire figyeljek használt autó vásárlásakor?",
        "Sedan vs SUV összehasonlítás városi vezetéshez"
      ],
      inputPlaceholder: 'Írd be a kérdésed ide...',
      sendButton: 'Küldés',
      clearChat: 'Beszélgetés Törlése',
      sampleResponse: 'Segítek az autókkal kapcsolatos kérdésekben! Ez egy helyőrző válasz. A jövőben mesterséges intelligencia fogja működtetni a rendszert, hogy részletes válaszokat adhass az autóvásárlással, karbantartással, összehasonlításokkal és még sok mással kapcsolatban.'
    },
    buyCars: {
      title: 'Autók Böngészése',
      subtitle: 'Találd meg a tökéletes autót a kollekciónkból',
      searchPlaceholder: 'Keresés márka vagy modell alapján...',
      filters: 'Szűrők',
      clearFilters: 'Összes Törlése',
      brandLabel: 'Márka',
      bodyTypeLabel: 'Karosszéria Típus',
      fuelTypeLabel: 'Üzemanyag Típus',
      colorLabel: 'Szín',
      yearLabel: 'Évjárat',
      kmLabel: 'Kilóméter',
      priceLabel: 'Ár ($)',
      resultsCount: 'Megjelenítve',
      cars: 'autó',
      noResults: 'Nem található autó',
      noResultsText: 'Próbáld meg módosítani a szűrőket vagy a keresést',
      viewOffer: 'Ajánlat Megtekintése'
    },
    carDetail: {
      notFound: 'Autó nem található',
      backToBrowse: 'Vissza a Böngészéshez',
      year: 'Évjárat',
      bodyType: 'Karosszéria',
      fuelType: 'Üzemanyag',
      transmission: 'Sebességváltó',
      kilometers: 'Kilóméter',
      power: 'Teljesítmény',
      color: 'Szín',
      location: 'Helyszín',
      features: 'Jellemzők',
      contactSeller: 'Eladó Elérése',
      scheduleTest: 'Próbavezetés Időpontja'
    },
    auth: {
      loginTitle: 'Üdvözlünk Vissza',
      loginSubtitle: 'Jelentkezz be a WheelWise fiókodba',
      registerTitle: 'Fiók Létrehozása',
      registerSubtitle: 'Csatlakozz a WheelWise-hoz még ma',
      name: 'Teljes Név',
      namePlaceholder: 'Add meg a neved',
      email: 'E-mail Cím',
      emailPlaceholder: 'Add meg az e-mail címed',
      password: 'Jelszó',
      passwordPlaceholder: 'Add meg a jelszavad',
      confirmPassword: 'Jelszó Megerősítése',
      confirmPasswordPlaceholder: 'Erősítsd meg a jelszavad',
      rememberMe: 'Emlékezz rám',
      forgotPassword: 'Elfelejtetted a jelszavad?',
      loginButton: 'Bejelentkezés',
      registerButton: 'Fiók Létrehozása',
      noAccount: 'Még nincs fiókod?',
      hasAccount: 'Már van fiókod?',
      signUp: 'Regisztráció',
      signIn: 'Bejelentkezés',
      orContinue: 'vagy folytasd a következővel',
      nameRequired: 'A név megadása kötelező',
      emailRequired: 'Az e-mail megadása kötelező',
      emailInvalid: 'Érvénytelen e-mail cím',
      passwordRequired: 'A jelszó megadása kötelező',
      passwordLength: 'A jelszónak legalább 6 karakter hosszúnak kell lennie',
      passwordMatch: 'A jelszavak nem egyeznek',
    },
    contact: {
      title: 'Kapcsolat',
      subtitle: 'Vedd fel velünk a kapcsolatot. Itt vagyunk, hogy segítsünk!',
      emailTitle: 'E-mail',
      phoneTitle: 'Telefon',
      addressTitle: 'Cím',
      formTitle: 'Küldj nekünk egy üzenetet',
      name: 'Teljes Név',
      namePlaceholder: 'Kiss János',
      email: 'E-mail Cím',
      emailPlaceholder: 'janos@pelda.hu',
      phone: 'Telefonszám',
      phonePlaceholder: '+36 20 123 4567',
      subject: 'Tárgy',
      subjectPlaceholder: 'Miben segíthetünk?',
      message: 'Üzenet',
      messagePlaceholder: 'Mesélj többet a kérdésedről...',
      submitButton: 'Üzenet Küldése',
      successTitle: 'Üzenet Elküldve!',
      successMessage: 'Köszönjük, hogy felvetted velünk a kapcsolatot. Hamarosan válaszolunk.',
      nameRequired: 'A név megadása kötelező',
      emailRequired: 'Az e-mail megadása kötelező',
      emailInvalid: 'Érvénytelen e-mail cím',
      subjectRequired: 'A tárgy megadása kötelező',
      messageRequired: 'Az üzenet megadása kötelező',
      messageLength: 'Az üzenetnek legalább 10 karakter hosszúnak kell lennie',
    },
    about: {
      title: 'A WheelWise-ról',
      subtitle: 'A Megbízható Platform Minőségi Járművek Vásárlásához és Eladásához',
      missionTitle: 'A Küldetésünk',
      missionText: 'A WheelWise-nál hiszünk abban, hogy egy autó vásárlása vagy eladása egyszerű, átlátható és élvezetes élmény legyen. Küldetésünk az autópiactér forradalmasítása azáltal, hogy összekötjük a vevőket és eladókat egy bizalomra, minőségre és innovációra épülő platformon keresztül.',
      missionText2: 'Elkötelezettek vagyunk az ellenőrzött hirdetések, biztonságos tranzakciók és kivételes ügyfélszolgálat biztosítása mellett, hogy minden felhasználó bizalommal találja meg a tökéletes járművét.',
      valuesTitle: 'Alapértékeink',
      value1Title: 'Bizalom és Átláthatóság',
      value1Desc: 'Minden hirdetés ellenőrzött és átlátható. Biztosítjuk, hogy minden információ pontos és megbízható.',
      value2Title: 'Biztonság Első',
      value2Desc: 'Az Ön biztonsága a prioritásunk. Fejlett biztonsági intézkedéseket használunk az adatok és tranzakciók védelmére.',
      value3Title: 'Ügyfélközpontú',
      value3Desc: 'Elkötelezett támogató csapatunk 24/7 rendelkezésre áll, hogy segítsen az út során.',
      value4Title: 'Innováció',
      value4Desc: 'Folyamatosan fejlesztjük platformunkat a legújabb technológiával, hogy javítsuk élményét.',
      statsTitle: 'Hatásunk',
      statCars: 'Hirdetett Autó',
      statUsers: 'Elégedett Felhasználó',
      statDeals: 'Sikeres Üzlet',
      statSatisfaction: 'Elégedettségi Arány',
      teamTitle: 'Ismerd Meg a Csapatunkat',
      teamDescription: 'Elkötelezett szakemberek dolgoznak együtt, hogy autóvásárlási és értékesítési élményed kivételes legyen.',
      ceoName: 'Kiss János',
      ceoRole: 'Vezérigazgató és Alapító',
      ctoName: 'Nagy Éva',
      ctoRole: 'Technológiai Igazgató',
      cooName: 'Szabó Péter',
      cooRole: 'Operatív Igazgató',
      ctaTitle: 'Készen Állsz a Kezdésre?',
      ctaText: 'Csatlakozz elégedett felhasználók ezreihez és tapasztald meg az autóvásárlás és -eladás jövőjét.',
      ctaBrowse: 'Autók Böngészése',
      ctaAskAI: 'AI Tanács',
    },
  },
  de: {
    nav: {
      home: 'Startseite',
      buyCars: 'Autos Kaufen',
      askAI: 'AI Fragen',
      about: 'Über Uns',
      contact: 'Kontakt',
      signIn: 'Anmelden',
    },
    home: {
      title: 'Finden Sie Ihr Perfektes Auto',
      subtitle: 'Ihr vertrauenswürdiger Marktplatz für den Kauf und Verkauf von Autos',
      description: 'Durchsuchen Sie Tausende von verifizierten Angeboten, kontaktieren Sie Verkäufer und fahren Sie mit Vertrauen.',
      ctaBuy: 'Autos Durchsuchen',
      ctaAskAI: 'oder fragen Sie die KI',
      featuresTitle: 'Warum WheelWise?',
      feature1Title: 'Verifizierte Angebote',
      feature1Desc: 'Alle Autos sind verifiziert und qualitätsgeprüft',
      feature2Title: 'Sichere Transaktionen',
      feature2Desc: 'Sichere und zuverlässige Zahlungsabwicklung',
      feature3Title: 'Expertenunterstützung',
      feature3Desc: '24/7 Kundensupport, um Ihnen zu helfen',
      statsTitle: 'Vertraut von Tausenden',
      statsCars: 'Aktive Angebote',
      statsUsers: 'Zufriedene Benutzer',
      statsDeals: 'Erfolgreiche Geschäfte',
    },
    askAI: {
      title: 'KI-Assistent',
      subtitle: 'Erhalten Sie sofortige Antworten auf Ihre Auto-Fragen',
      welcomeTitle: 'Wie kann ich Ihnen heute helfen?',
      welcomeText: 'Fragen Sie mich alles über Autos, Kauftipps, Wartung, Vergleiche und mehr!',
      suggestedTitle: 'Versuchen Sie zu fragen:',
      suggestedQuestions: [
        "Was ist der beste Familien-SUV unter 30.000 €?",
        "Wie prüfe ich, ob ein Gebrauchtwagen einen Unfall hatte?",
        "Worauf sollte ich beim Kauf eines Gebrauchtwagens achten?",
        "Limousine vs SUV für Stadtfahrten vergleichen"
      ],
      inputPlaceholder: 'Geben Sie Ihre Frage hier ein...',
      sendButton: 'Senden',
      clearChat: 'Chat Löschen',
      sampleResponse: 'Ich bin hier, um Ihnen bei autobezogenen Fragen zu helfen! Dies ist eine Platzhalterantwort. In Zukunft werde ich von KI angetrieben, um detaillierte Antworten zu Autokauf, Wartung, Vergleichen und mehr zu geben.'
    },
    buyCars: {
      title: 'Autos Durchsuchen',
      subtitle: 'Finden Sie Ihr perfektes Auto aus unserer Sammlung',
      searchPlaceholder: 'Suche nach Marke oder Modell...',
      filters: 'Filter',
      clearFilters: 'Alle Löschen',
      brandLabel: 'Marke',
      bodyTypeLabel: 'Karosserietyp',
      fuelTypeLabel: 'Kraftstoffart',
      colorLabel: 'Farbe',
      yearLabel: 'Jahr',
      kmLabel: 'Kilometer',
      priceLabel: 'Preis ($)',
      resultsCount: 'Anzeigen',
      cars: 'Autos',
      noResults: 'Keine Autos gefunden',
      noResultsText: 'Versuchen Sie, Ihre Filter oder Suchanfrage anzupassen',
      viewOffer: 'Angebot Ansehen'
    },
    carDetail: {
      notFound: 'Auto nicht gefunden',
      backToBrowse: 'Zurück zum Durchsuchen',
      year: 'Jahr',
      bodyType: 'Karosserietyp',
      fuelType: 'Kraftstoffart',
      transmission: 'Getriebe',
      kilometers: 'Kilometer',
      power: 'Leistung',
      color: 'Farbe',
      location: 'Standort',
      features: 'Ausstattung',
      contactSeller: 'Verkäufer Kontaktieren',
      scheduleTest: 'Probefahrt Vereinbaren'
    },
    auth: {
      loginTitle: 'Willkommen Zurück',
      loginSubtitle: 'Melden Sie sich bei Ihrem WheelWise-Konto an',
      registerTitle: 'Konto Erstellen',
      registerSubtitle: 'Treten Sie WheelWise noch heute bei',
      name: 'Vollständiger Name',
      namePlaceholder: 'Geben Sie Ihren vollständigen Namen ein',
      email: 'E-Mail-Adresse',
      emailPlaceholder: 'Geben Sie Ihre E-Mail ein',
      password: 'Passwort',
      passwordPlaceholder: 'Geben Sie Ihr Passwort ein',
      confirmPassword: 'Passwort Bestätigen',
      confirmPasswordPlaceholder: 'Bestätigen Sie Ihr Passwort',
      rememberMe: 'Angemeldet bleiben',
      forgotPassword: 'Passwort vergessen?',
      loginButton: 'Anmelden',
      registerButton: 'Konto Erstellen',
      noAccount: 'Sie haben noch kein Konto?',
      hasAccount: 'Sie haben bereits ein Konto?',
      signUp: 'Registrieren',
      signIn: 'Anmelden',
      orContinue: 'oder fortfahren mit',
      nameRequired: 'Name ist erforderlich',
      emailRequired: 'E-Mail ist erforderlich',
      emailInvalid: 'E-Mail ist ungültig',
      passwordRequired: 'Passwort ist erforderlich',
      passwordLength: 'Passwort muss mindestens 6 Zeichen lang sein',
      passwordMatch: 'Passwörter stimmen nicht überein',
    },
    contact: {
      title: 'Kontaktieren Sie Uns',
      subtitle: 'Nehmen Sie Kontakt mit unserem Team auf. Wir sind hier, um zu helfen!',
      emailTitle: 'E-Mail',
      phoneTitle: 'Telefon',
      addressTitle: 'Adresse',
      formTitle: 'Senden Sie uns eine Nachricht',
      name: 'Vollständiger Name',
      namePlaceholder: 'Max Mustermann',
      email: 'E-Mail-Adresse',
      emailPlaceholder: 'max@beispiel.de',
      phone: 'Telefonnummer',
      phonePlaceholder: '+36 20 123 4567',
      subject: 'Betreff',
      subjectPlaceholder: 'Wie können wir helfen?',
      message: 'Nachricht',
      messagePlaceholder: 'Erzählen Sie uns mehr über Ihre Anfrage...',
      submitButton: 'Nachricht Senden',
      successTitle: 'Nachricht Gesendet!',
      successMessage: 'Vielen Dank für Ihre Kontaktaufnahme. Wir werden uns bald bei Ihnen melden.',
      nameRequired: 'Name ist erforderlich',
      emailRequired: 'E-Mail ist erforderlich',
      emailInvalid: 'E-Mail ist ungültig',
      subjectRequired: 'Betreff ist erforderlich',
      messageRequired: 'Nachricht ist erforderlich',
      messageLength: 'Nachricht muss mindestens 10 Zeichen lang sein',
    },
    about: {
      title: 'Über WheelWise',
      subtitle: 'Ihre Vertrauenswürdige Plattform für den Kauf und Verkauf Hochwertiger Fahrzeuge',
      missionTitle: 'Unsere Mission',
      missionText: 'Bei WheelWise glauben wir, dass der Kauf oder Verkauf eines Autos ein einfaches, transparentes und angenehmes Erlebnis sein sollte. Unsere Mission ist es, den Automobilmarkt zu revolutionieren, indem wir Käufer und Verkäufer über eine Plattform verbinden, die auf Vertrauen, Qualität und Innovation basiert.',
      missionText2: 'Wir verpflichten uns, verifizierte Angebote, sichere Transaktionen und außergewöhnlichen Kundenservice zu bieten, damit jeder Benutzer sein perfektes Fahrzeug mit Vertrauen findet.',
      valuesTitle: 'Unsere Kernwerte',
      value1Title: 'Vertrauen & Transparenz',
      value1Desc: 'Jedes Angebot ist verifiziert und transparent. Wir stellen sicher, dass alle Informationen genau und vertrauenswürdig sind.',
      value2Title: 'Sicherheit Zuerst',
      value2Desc: 'Ihre Sicherheit ist unsere Priorität. Wir verwenden fortschrittliche Sicherheitsmaßnahmen zum Schutz Ihrer Daten und Transaktionen.',
      value3Title: 'Kundenorientiert',
      value3Desc: 'Unser engagiertes Support-Team steht Ihnen rund um die Uhr zur Verfügung, um Sie während Ihrer Reise zu unterstützen.',
      value4Title: 'Innovation',
      value4Desc: 'Wir verbessern unsere Plattform kontinuierlich mit der neuesten Technologie, um Ihr Erlebnis zu verbessern.',
      statsTitle: 'Unsere Wirkung',
      statCars: 'Gelistete Autos',
      statUsers: 'Zufriedene Benutzer',
      statDeals: 'Erfolgreiche Geschäfte',
      statSatisfaction: 'Zufriedenheitsrate',
      teamTitle: 'Lernen Sie Unser Team Kennen',
      teamDescription: 'Engagierte Fachleute arbeiten zusammen, um Ihr Auto-Kauf- und Verkaufserlebnis außergewöhnlich zu machen.',
      ceoName: 'Hans Schmidt',
      ceoRole: 'CEO & Gründer',
      ctoName: 'Anna Weber',
      ctoRole: 'CTO',
      cooName: 'Thomas Müller',
      cooRole: 'COO',
      ctaTitle: 'Bereit Loszulegen?',
      ctaText: 'Schließen Sie sich Tausenden zufriedener Benutzer an und erleben Sie die Zukunft des Autokaufs und -verkaufs.',
      ctaBrowse: 'Autos Durchsuchen',
      ctaAskAI: 'AI Fragen',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        changeLanguage,
        translations: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
